In [39]:
import itertools
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.ticker import NullFormatter
import pandas as pd
import matplotlib.ticker as ticker
from sklearn import preprocessing
%matplotlib inline

In [40]:
df=pd.read_csv('custcat.csv')
df.head()

region  tenure  age  marital  address  income  ed  employ  retire  gender  \
0       2      13   44        1        9    64.0   4       5     0.0       0   
1       3      11   33        1        7   136.0   5       5     0.0       0   
2       3      68   52        1       24   116.0   1      29     0.0       1   
3       2      33   33        0       12    33.0   2       0     0.0       1   
4       2      23   30        1        9    30.0   1       2     0.0       0   

   reside  custcat  
0       2        1  
1       6        4  
2       2        3  
3       1        1  
4       4        3

In [46]:
df['custcat'].value_counts()

3    281
1    266
4    236
2    217
Name: custcat, dtype: int64

In [41]:
df.columns

Index(['region', 'tenure', 'age', 'marital', 'address', 'income', 'ed',
       'employ', 'retire', 'gender', 'reside', 'custcat'],
      dtype='object')

In [42]:
X=df[['region', 'tenure', 'age', 'income', 'marital', 'address', 'ed',
       'employ', 'retire', 'gender', 'reside']].values
X[0:5]

array([[  2.,  13.,  44.,  64.,   1.,   9.,   4.,   5.,   0.,   0.,   2.],
       [  3.,  11.,  33., 136.,   1.,   7.,   5.,   5.,   0.,   0.,   6.],
       [  3.,  68.,  52., 116.,   1.,  24.,   1.,  29.,   0.,   1.,   2.],
       [  2.,  33.,  33.,  33.,   0.,  12.,   2.,   0.,   0.,   1.,   1.],
       [  2.,  23.,  30.,  30.,   1.,   9.,   1.,   2.,   0.,   0.,   4.]])

In [43]:
y=df['custcat'].values
y[0:5]

array([1, 4, 3, 1, 3], dtype=int64)

In [44]:
#Normalize Data
X = preprocessing.StandardScaler().fit(X).transform(X.astype(float))
X[0:5]

array([[-0.02696767, -1.055125  ,  0.18450456, -0.12650641,  1.0100505 ,
        -0.25303431,  1.0877526 , -0.5941226 , -0.22207644, -1.03459817,
        -0.23065004],
       [ 1.19883553, -1.14880563, -0.69181243,  0.54644972,  1.0100505 ,
        -0.4514148 ,  1.9062271 , -0.5941226 , -0.22207644, -1.03459817,
         2.55666158],
       [ 1.19883553,  1.52109247,  0.82182601,  0.35951747,  1.0100505 ,
         1.23481934, -1.36767088,  1.78752803, -0.22207644,  0.96655883,
        -0.23065004],
       [-0.02696767, -0.11831864, -0.69181243, -0.41625141, -0.9900495 ,
         0.04453642, -0.54919639, -1.09029981, -0.22207644,  0.96655883,
        -0.92747794],
       [-0.02696767, -0.58672182, -0.93080797, -0.44429125,  1.0100505 ,
        -0.25303431, -1.36767088, -0.89182893, -0.22207644, -1.03459817,
         1.16300577]])

In [47]:
#TRAIN TEST SPLIT
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size = 0.3, random_state = 4)
print('Train set:', X_train.shape, y_train.shape)
print('Test set:', X_test.shape, y_test.shape)

Train set: (700, 11) (700,)
Test set: (300, 11) (300,)


In [48]:
from sklearn.neighbors import KNeighborsClassifier

In [51]:
k = 3
neigh = KNeighborsClassifier(n_neighbors = k).fit(X_train, y_train)
neigh

KNeighborsClassifier(n_neighbors=3)

In [50]:
#PREDICTION
yhat = neigh.predict(X_test)
yhat[0:5]

array([3, 1, 3, 2, 4], dtype=int64)

In [52]:
#ACCURACY
from sklearn import metrics
print("Train set Accuracy: ", metrics.accuracy_score(y_train, neigh.predict(X_train)))
print("Test set Accuracy: ", metrics.accuracy_score(y_test, yhat))

Train set Accuracy:  0.5642857142857143
Test set Accuracy:  0.33


In [53]:
#AGAIN WITH K=9
k = 9
neigh = KNeighborsClassifier(n_neighbors = k).fit(X_train,y_train)
neigh

yhat = neigh.predict(X_test)
yhat[0:5]

from sklearn import metrics
print("Train set Accuracy: ", metrics.accuracy_score(y_train, neigh.predict(X_train)))
print("Test set Accuracy: ", metrics.accuracy_score(y_test, yhat))

Train set Accuracy:  0.5014285714285714
Test set Accuracy:  0.32666666666666666


# SVM MODEL

In [58]:
#divide the data into attributes and labels, execute the following code:
X = df.drop('custcat', axis=1)
y = df['custcat']

In [59]:
#TRAIN TEST SPLIT 70 %  AND 30%
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30)

In [60]:
#TAINING THE ALGORITHM
from sklearn.svm import SVC
svclassifier = SVC(kernel='linear')
svclassifier.fit(X_train, y_train)

SVC(kernel='linear')

In [62]:
#PREDICTION
y_pred = svclassifier.predict(X_test)
y[0:5]

0    1
1    4
2    3
3    1
4    3
Name: custcat, dtype: int64

In [64]:
#EVALUATION OF ALGORITHM
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[44  1 21 16]
 [10 14 14 25]
 [22 13 40 17]
 [15  5 13 30]]
              precision    recall  f1-score   support

           1       0.48      0.54      0.51        82
           2       0.42      0.22      0.29        63
           3       0.45      0.43      0.44        92
           4       0.34      0.48      0.40        63

    accuracy                           0.43       300
   macro avg       0.43      0.42      0.41       300
weighted avg       0.43      0.43      0.42       300



In [ ]:
[152    0]
 [  1  122]]
              precision   recall   f1-score   support

           0       0.99     1.00       1.00       152
           1       1.00     0.99       1.00       123

avg / total        1.00     1.00       1.00       275